 =

Event Start

	/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */

	&ImprimirTotalDebCred.TooltipText = "Imprimir Totais de Debito e Credito "

	/* Generated by DVelop Work With Plus Pattern [End] - Do not change */

	LoadWWPContext(&Context)
    &CTBUsuId			= &Context.CTBUsuId
    &CTBUsuNome			= &Context.CTBUsuNome
	&CTBEmpId			= &Context.CTBEmpId
	&CTBEmpRazaoSocial	= &Context.CTBEmpRazaoSocial
	
//-------------filtros-------------------------------
//	&ImprimeTodasContas        = False
//	&ImprimeCentroCusto        = False
//	&ImprimeCodRed             = False
//	&ImprimeContasSemMov       = False
//	&ImprimePaginaEntreContas  = False
//	&ImprimeTotalDia           = False 
//	&ImprimeTotalMes           = False
//	&ImprimirTotalDebCred      = False
//-----------------------------------------------------------------------------------	
	//&CTBLancDatainicio = Today()
	&CTBLancDatafinal = Today()

EndEvent

Event Enter

	/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */



	/* Generated by DVelop Work With Plus Pattern [End] - Do not change */

	If NOT &CTBLancDatainicio.IsEmpty() OR NOT &CTBLancDatafinal.IsEmpty()
		If &ImprimeTodasContas = True				
			RCTBRazaoAnalitico.Call(&CTBLancDatainicio, &CTBLancDatafinal, '', '', &ImprimeTodasContas, &ImprimeCentroCusto, &ImprimeCodRed, 
			&ImprimeContasSemMov, &ImprimePaginaEntreContas, &ImprimeTotalDia, &ImprimeTotalMes, &ImprimirTotalDebCred)		
		Else
			RCTBRazaoAnalitico.Call(&CTBLancDatainicio, &CTBLancDatafinal, &CTBPlanoContaInicio, &CTBPlanoContaFinal, &ImprimeTodasContas,
	 		&ImprimeCentroCusto, &ImprimeCodRed, &ImprimeContasSemMov, &ImprimePaginaEntreContas, &ImprimeTotalDia, &ImprimeTotalMes,
	 		 &ImprimirTotalDebCred)	
		EndIf
	Else
		Msg('Preencha a data inicial e final.')
	EndIf

EndEvent

Event &ImprimeTodasContas.IsValid

	If &ImprimeTodasContas = True
		TextBlockCTBPlanoContaInicio.Visible = False
		&CTBPlanoContaInicio.Visible 		 = False
		TextBlockCTBPlanoContaFinal.Visible  = False
		&CTBPlanoContaFinal.Visible  		 = False
	Else
		TextBlockCTBPlanoContaInicio.Visible = True
		&CTBPlanoContaInicio.Visible 		 = True
		TextBlockCTBPlanoContaFinal.Visible  = True
		&CTBPlanoContaFinal.Visible 		 = True
	EndIf

EndEvent

Event &ImprimeTotalDia.IsValid

	If &ImprimeTotalDia = True
		TextBlockImprimeTotalMes.Visible = False
		&ImprimeTotalMes.Visible 		 = False
	Else
		TextBlockImprimeTotalMes.Visible = True
		&ImprimeTotalMes.Visible 		 = True
	EndIf

EndEvent

Event &ImprimeTotalMes.IsValid

	If &ImprimeTotalMes = True
		TextBlockImprimeTotalDia.Visible = False
		&ImprimeTotalDia.Visible 		 = False
	Else
		TextBlockImprimeTotalDia.Visible = True
		&ImprimeTotalDia.Visible 		 = True
	EndIf

EndEvent


