Event Start

LoadWWPContext(&Context)

	/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */



	/* Generated by DVelop Work With Plus Pattern [End] - Do not change */

	&CTBLancDataEntradaInicial = YMDtoD(Year(&Today), 1, 1)
	&CTBLancDataEntradaFinal = &Today

EndEvent

Event Enter

	/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */



	/* Generated by DVelop Work With Plus Pattern [End] - Do not change */

	DO Case
		Case &TermoRazao
			
        InNewWindow1.Target	= RCTBRazaoAnalitico.Link(&CTBLancDataEntradaInicial, &CTBLancDataEntradaFinal, , , , , , , , , , , , , , ,&TermoRazao,&NrPagRazao, &TermoDiario, &NrPgDiario ,&TermoLivro, &NrPagLivro)
                    InNewWindow1.Name	= '_blank'
                    InNewWindow1.OpenWindow()
			
		Case &TermoDiario
			InNewWindow1.Target	= RCTBDiarioAuxiliar.Link(&CTBLancDataEntradaInicial, &CTBLancDataEntradaFinal, ,  , , ,  , , ,  ,  , ,  , , , , &TermoRazao,&NrPagRazao, &TermoDiario, &NrPgDiario ,&TermoLivro, &NrPagLivro)
			InNewWindow1.Name	= '_blank'
			InNewWindow1.OpenWindow()
		Case &TermoLivro
			 InNewWindow1.Target= RCTBLivroCaixa.link( &CTBLancDataEntradaInicial, &CTBLancDataEntradaFinal, , , , , , , , , , , , , , , &TermoRazao,&NrPagRazao, &TermoDiario, &NrPgDiario ,&TermoLivro, &NrPagLivro)
				InNewWindow1.Name	= '_blank'
			InNewWindow1.OpenWindow()
		Endcase

EndEvent


